### ISSUE TITLE
Planning v2 release

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#359]
(This are some ideas and we're open to suggestions)

## Main goals

* Make it easier to maintain
  * Support fewer versions of ember/ember-cli (just 3.0 and above?)
* Remove jQuery dependency
* Support for RFC268 tests (see #357)
* Clean up API
  * New collection API (see #352, #347 and #345)
  * Cleanup API options, helpers, requires, etc.
* Site redesign with ember-cli-addon-docs (#353)
* Migration path from v1.14
* Dedicated deprecations page in the guide (#465) 
* Adapters (#479) 
* Embroider compatibitlity (https://github.com/san650/ember-cli-page-object/issues/539)

## Deprecations

* [x] v1.4 will include the new collection API with deprecation warnings
* [x] [multiple selectors (group)](https://github.com/san650/ember-cli-page-object/issues/335#issuecomment-344248732)
  * [x] v1: deprecate 
  * [x] v2: replace deprecated code with error
* [x] Drop `page.render()`
* [X] imports from test-support https://github.com/san650/ember-cli-page-object/pull/368
* [x] `is` https://github.com/san650/ember-cli-page-object/issues/442
* [x] deprecate findElement/findElementWithAssert #463 
* [x] deprecate `url` in `create` https://github.com/san650/ember-cli-page-object/issues/464
* [x] deprecate `setContext` (#448)
* [x] deprecate `multiple`
* [x] `string-properties-on-definition` deprecation 
  * [x] v1: deprecate 
  * [x] v2: replace deprecation with an error
* [x] `create-url-argument` deprecation 
  * [x] v1: deprecate 
  * [x] v2: remove deprecated code
* [x] update "/docs/guides". Make sure migration page is up to date

**Comment by ro0gr** [comment]
> Remove jQuery dependency

I think in order to achieve that in v2, we should plan deprecations for APIs which are directly bound to jquery, like `is`, `findElement`, and probably others

**Comment by yratanov** [comment]
can I help with this?

**Comment by ro0gr** [comment]
@yratanov Thanks for the interest!

I believe there are few more things needed. I'll work to create missing tickets and update this one today.

**Comment by SergeAstapov** [comment]
@ro0gr @san650 out of curiosity, did you change plans regarding V2 or do you consider it "close to be done"?

**Comment by ro0gr** [comment]
@SergeAstapov Not sure why the issue was actually closed, maybe it is so due to majority of the tasks listed in this ticket has been done.  I'm definitely interested in moving v2 release to completion. Hope to dedicate some time to continue working on it(hopefuly this year).

**Comment by SergeAstapov** [comment]
@ro0gr can you think of some tasks I potentially may be able to help with?

**Comment by ro0gr** [comment]
@SergeAstapov There are 2 general things to be done in the v2 branch: 
 - upgrade ember(+remove old stuff which doesn't make sense anymore)
 - embroider compatibility

Currently I have these two mixed locally in 1 large branch, I plan to split it into 2 PRs to get a better picture of what's left to be done. Once I do it, I will create a follow up tasks which can be parallelized.

**Comment by san650** [comment]
@SergeAstapov @ro0gr sorry I didn't know the issue was still being in use. I was cleaning some of my old PRs/Issues and closed this one (since it is from 2018). I can reopen if you think it's useful

**Comment by ro0gr** [comment]
@san650 np, ok, reopened.

**Comment by patocallaghan** [comment]
Hey @ro0gr 👋, just wondering should we also consider adding the Ember v4 upgrade + v2 Addon migration changes here too as part of this major version bump, or would that be v3?

**Comment by ro0gr** [comment]
@patocallaghan I'd love it to become v2 addon before releasing the new major. But don't want to have it as a requirement, cause TBH, I'm not sure if I manage to dedicate enough time for this kind of convertion in a foreseeable future. So if anyone would do it, I'd gladly include it before the v2 stable release.

**Comment by SergeAstapov** [comment]
> @patocallaghan I'd love it to become v2 addon before releasing the new major. But don't want to have it as a requirement, cause TBH, I'm not sure if I manage to dedicate enough time for this kind of convertion in a foreseeable future. So if anyone would do it, I'd gladly include it before the v2 stable release.

I can help with v2 conversion, already did for couple of addons

**Comment by acorncom** [comment]
https://github.com/NullVoxPopuli/ember-addon-migrator might also be useful

**Comment by ro0gr** [comment]
I've created an issue for migration https://github.com/san650/ember-cli-page-object/issues/575

**Comment by rtablada** [comment]
What are the remaining steps to releasing 2.x as a full release instead of beta?

Currently 1.x versions cause dot access deprecation warnings because of the dependency of dom helpers: https://github.com/san650/ember-cli-page-object/issues/592 which blocks potential 4.x upgrades or apps to be on supported Ember LTS.

**Comment by ro0gr** [comment]
@rtablada you are right. Let's move this forward. I've just updated bullet points with obviously missing steps. 
I believe mostly we should remove the remaining deprecations properly. Also I believe I've noticed some non-critical issues with error messages which I'd like to fix before the release(need to recheck).

I'll try to come back to this topic this week, and keep this ticket updated.

**Comment by ro0gr** [comment]
Thanks everyone for support! I think we are finally done here.
